import React, { useState, useCallback, useRef } from 'react';
import { Mine, MineType, LogEntry, ModalState } from './types';
import { DetectionView } from './components/DetectionView';
import { LogConsole } from './components/LogConsole';
import { Modal } from './components/Modal';
import { getThreatAssessment, playEODProtocol } from './services/gemini';

const App: React.FC = () => {
  const [imageSrc, setImageSrc] = useState<string | null>(null);
  const [mines, setMines] = useState<Mine[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [isGeminiLoading, setIsGeminiLoading] = useState(false);
  
  const [modalState, setModalState] = useState<ModalState>({
    isOpen: false,
    title: '',
    content: '',
    type: 'info'
  });

  // Helper to add log
  const addLog = useCallback((message: string, type: 'INFO' | 'ALERT' | 'ERROR' = 'INFO') => {
    const entry: LogEntry = {
      id: Math.random().toString(36).substr(2, 9),
      timestamp: new Date().toLocaleTimeString('en-US', { hour12: false }),
      message,
      type
    };
    setLogs(prev => [...prev, entry]);
  }, []);

  // Handle File Upload
  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        if (typeof e.target?.result === 'string') {
          setImageSrc(e.target.result);
          setMines([]);
          addLog(`Image loaded: ${file.name}`, 'INFO');
          runSimulation();
        }
      };
      reader.onerror = () => addLog("Failed to read file", "ERROR");
      reader.readAsDataURL(file);
    }
  };

  // Run Simulation
  const runSimulation = () => {
    setIsAnalyzing(true);
    addLog("Starting YOLOv8 inference simulation...", "INFO");

    setTimeout(() => {
      const numMines = Math.floor(Math.random() * 5) + 3; // 3 to 7 mines
      const newMines: Mine[] = [];
      const types = [MineType.AP_MINE, MineType.AT_MINE, MineType.UXO];

      for (let i = 0; i < numMines; i++) {
        newMines.push({
          id: Math.random().toString(36).substr(2, 9),
          xPct: Math.random() * 90 + 5, // Avoid extreme edges
          yPct: Math.random() * 90 + 5,
          lat: 34.0000 + (Math.random() * 0.1),
          lon: -118.0000 + (Math.random() * 0.1),
          confidence: Math.random() * 0.2 + 0.8,
          type: types[Math.floor(Math.random() * types.length)]
        });
      }

      setMines(newMines);
      setIsAnalyzing(false);
      addLog(`Scan Complete. ${numMines} potential hazards detected.`, 'ALERT');
    }, 2500);
  };

  const handleReset = () => {
    setImageSrc(null);
    setMines([]);
    setLogs([]);
    addLog("System Reset. Awaiting input.", "INFO");
  };

  const handleThreatAssessment = async () => {
    if (mines.length === 0) return;
    setIsGeminiLoading(true);
    addLog("Requesting AI Threat Assessment...", "INFO");

    try {
      const result = await getThreatAssessment(mines);
      setModalState({
        isOpen: true,
        title: 'THREAT ASSESSMENT',
        content: result,
        type: 'success',
        footer: 'Analysis provided by Gemini 2.5 Flash'
      });
      addLog("Threat Assessment received successfully.", "INFO");
    } catch (error: any) {
      setModalState({
        isOpen: true,
        title: 'CONNECTION ERROR',
        content: error.message,
        type: 'error'
      });
      addLog(`Threat Assessment Failed: ${error.message}`, "ERROR");
    } finally {
      setIsGeminiLoading(false);
    }
  };

  const handleEODProtocol = async () => {
    if (mines.length === 0) return;
    setIsGeminiLoading(true);
    
    // Pick the most dangerous or first mine
    const targetMine = mines.find(m => m.type === MineType.UXO) || mines.find(m => m.type === MineType.AT_MINE) || mines[0];
    
    addLog(`Initiating EOD Protocol generation for ${targetMine.type}...`, "INFO");

    try {
      await playEODProtocol(targetMine.type);
      setModalState({
        isOpen: true,
        title: 'AUDIO BROADCAST',
        content: `Voice Protocol for ${targetMine.type} is now playing on secured channel.\n\nType: ${targetMine.type}\nCoords: ${targetMine.lat.toFixed(4)}, ${targetMine.lon.toFixed(4)}`,
        type: 'warning',
        footer: 'Audio generated by Gemini 2.5 Flash TTS'
      });
      addLog("EOD Voice Protocol broadcasted.", "INFO");
    } catch (error: any) {
      setModalState({
        isOpen: true,
        title: 'AUDIO GENERATION ERROR',
        content: error.message,
        type: 'error'
      });
      addLog(`EOD Protocol Failed: ${error.message}`, "ERROR");
    } finally {
      setIsGeminiLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-950 p-4 md:p-8 font-mono relative">
      <div className="max-w-5xl mx-auto space-y-6">
        
        {/* Header */}
        <header className="flex flex-col md:flex-row justify-between items-center border-b border-gray-800 pb-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-black text-orange-500 tracking-tighter uppercase">
              UAV <span className="text-gray-100">Sentinel</span> Interface
            </h1>
            <p className="text-xs text-green-500 mt-1 tracking-widest font-bold">REAL-TIME THREAT DETECTION SYSTEM V2.5</p>
          </div>
          <div className="mt-4 md:mt-0 flex items-center space-x-3">
             <div className="flex flex-col items-end">
               <span className="text-[10px] text-gray-500">API STATUS</span>
               <span className="text-xs text-green-400 font-bold">ONLINE</span>
             </div>
             <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse"></div>
          </div>
        </header>

        {/* Controls */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Main View Area */}
          <div className="lg:col-span-2 space-y-6">
             <DetectionView 
               imageSrc={imageSrc} 
               mines={mines} 
               isAnalyzing={isAnalyzing}
               onMineClick={(mine) => addLog(`Selected Marker #${mine.id.slice(0,4)}: ${mine.type} (${(mine.confidence*100).toFixed(0)}%)`, 'INFO')}
             />
             <LogConsole logs={logs} />
          </div>

          {/* Sidebar / Command Panel */}
          <div className="space-y-6">
            
            {/* Input Section */}
            <div className="bg-gray-900 border border-gray-700 p-5 rounded-lg shadow-lg">
              <h2 className="text-sm font-bold text-gray-400 mb-4 border-l-4 border-orange-500 pl-2">SENSOR INPUT</h2>
              <div className="space-y-3">
                <label className="flex items-center justify-center w-full px-4 py-4 bg-gray-800 border-2 border-dashed border-gray-600 rounded-lg cursor-pointer hover:border-orange-500 hover:bg-gray-750 transition-all group">
                  <div className="text-center">
                    <span className="block text-gray-400 group-hover:text-orange-400 text-sm font-bold">UPLOAD IMAGERY</span>
                    <span className="block text-gray-600 text-[10px] mt-1">SUPPORTED: JPG, PNG</span>
                  </div>
                  <input type="file" className="hidden" accept="image/*" onChange={handleFileUpload} />
                </label>
                <button 
                  onClick={handleReset}
                  className="w-full py-3 bg-red-900/50 hover:bg-red-800 text-red-200 text-xs font-bold rounded border border-red-700 transition-colors uppercase"
                >
                  Reset System
                </button>
              </div>
            </div>

            {/* AI Action Section */}
            <div className="bg-gray-900 border border-gray-700 p-5 rounded-lg shadow-lg relative overflow-hidden">
               {isGeminiLoading && (
                 <div className="absolute inset-0 bg-black/60 z-10 flex items-center justify-center backdrop-blur-[1px]">
                   <div className="animate-spin h-8 w-8 border-2 border-t-green-500 border-gray-600 rounded-full"></div>
                 </div>
               )}
              
              <h2 className="text-sm font-bold text-gray-400 mb-4 border-l-4 border-green-500 pl-2">AI COMMANDS</h2>
              <div className="space-y-3">
                <button
                  onClick={handleThreatAssessment}
                  disabled={mines.length === 0 || isGeminiLoading}
                  className="w-full py-4 bg-gray-800 hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed border-l-4 border-green-600 text-left px-4 flex justify-between items-center transition-all group"
                >
                  <div>
                    <span className="block text-gray-200 font-bold text-sm group-hover:text-green-400">THREAT ASSESSMENT</span>
                    <span className="block text-gray-500 text-[10px]">GEMINI 2.5 FLASH ANALYSIS</span>
                  </div>
                  <svg className="w-5 h-5 text-gray-600 group-hover:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                  </svg>
                </button>

                <button
                  onClick={handleEODProtocol}
                  disabled={mines.length === 0 || isGeminiLoading}
                  className="w-full py-4 bg-gray-800 hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed border-l-4 border-blue-600 text-left px-4 flex justify-between items-center transition-all group"
                >
                  <div>
                    <span className="block text-gray-200 font-bold text-sm group-hover:text-blue-400">EOD VOICE PROTOCOL</span>
                    <span className="block text-gray-500 text-[10px]">GEMINI TTS GENERATION</span>
                  </div>
                  <svg className="w-5 h-5 text-gray-600 group-hover:text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.536 8.464a5 5 0 000 7.072m-2.828-9.9a9 9 0 000 12.728M12 12h.01" />
                  </svg>
                </button>
              </div>
            </div>

            {/* Status Panel */}
            <div className="bg-gray-800/50 p-4 rounded text-center border border-gray-700">
               <span className="text-gray-500 text-[10px] uppercase block mb-1">Active Hazards Detected</span>
               <span className="text-4xl font-black text-orange-500">{mines.length}</span>
            </div>

          </div>
        </div>
      </div>

      <Modal 
        state={modalState} 
        onClose={() => setModalState(prev => ({ ...prev, isOpen: false }))} 
      />
    </div>
  );
};

export default App;